### ISSUE TITLE
tutorials (write notebook structure with comments or something)

### ISSUE THREAD

**Issue by strasserle** [theislab/spapros#204]
- [x]  divide into basic and advanced, selection and evaluation @strasserle 
- [x] change dataset @strasserle 
- [x] add outline @strasserle 
- [x] hide warnings @strasserle
- [x] proof reading @LouisK92 
- [x] add figures @LouisK92
- [x] probe design tutorial

**Comment by Zethson** [comment]
I recently created a sphinx-gallery setup for ehrapy. Looks like this: https://ehrapy.readthedocs.io/en/development/tutorials/index.html

I can transfer it to spapros eventually when you're ready.
