### ISSUE TITLE
Is it possible to save the probeselector to a file?

### ISSUE THREAD

**Issue by pakiessling** [theislab/spapros#231]
Hi, thank you for the tool and congratulations on the preprint.

I am running spapros on the command line.

After a run is finished I want to plot the selector, `masked_dotplot, plot_gene_overlap() ` ect in a separate file.

Is the selector object saved somewhere in the results folder or how do I archieve that?

I tried to pickle it but ran into some problems related to the multiprocessing

**Comment by LouisK92** [comment]
Hi! 

You can reload the saved output by creating another `ProbesetSelector` object with the same `save_dir` and running `select_probeset` (this method loads results if they already exist). Importantly also the arguments `adata` and `celltype_key` need to be the same as in the initial selection.

Example:
```python
# first run
import spapros as sp
adata = sp.ut.get_processed_pbmc_data()
selector = sp.se.ProbesetSelector(adata, "celltype", n=30, verbosity=0, save_dir="./selection/")
selector.select_probeset()
sp.pl.masked_dotplot(adata,selector)

del selector

# Load from save_dir
selector = sp.se.ProbesetSelector(adata, "celltype", n=30, verbosity=0, save_dir="./selection/")
selector.select_probeset()
sp.pl.masked_dotplot(adata,selector)
```

You mentioned you're running spapros on the command line though. The cli functions are not maintained atm, did you use those or did you wrap the Selector similar to my code example?

**Comment by LouisK92** [comment]
- [ ] I guess it would be good to add some function `load_selector(save_dir, adata)`. 

I think saving the whole selector e.g. via pickle is unfortunately not the way to go since it would include the data object `selector.adata`.

**Comment by pakiessling** [comment]
Thank you, that works fine.

I wrapped the functions like in your example
