### ISSUE TITLE
Metaclass TypeError

### ISSUE THREAD

**Issue by simomounir** [theislab/spapros#253]
**TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases**

**To Reproduce**

1. I am using Python 3.9 under a windows 10 machine
2. Spapros is pip-installable without issues
3. when trying  "import spapros as sp"  I get the error described above. Where does this error come from? Stacktrace provides this info:

**Expected behavior**
importing the spapros package with success and managing to at least run "**print(f"spapros=={sp.__version__}")**"

**System**

-   OS:  [Windows 10 pro]
-   Language Version: [e.g. Python 3.9]
-   No virtual environment.

**Additional context**

**Comment by LouisK92** [comment]
thx for opening. can reproduce the error - i guess some new dependency issue. will look into it

**Comment by LouisK92** [comment]
Should be fixed now with the new release (0.1.2).

Wrt your code snippet pls try 
```python
import spapros as sp
print(f"spapros=={sp.__version__}")
```
