### ISSUE TITLE
masked_dotplot does not allow NaNs in selector.probeset["celltypes_marker"]

### ISSUE THREAD

**Issue by jwrth** [theislab/spapros#268]
**Describe the bug**

Hi, I ran spapros following the "advanced probeset selection" tutorial with Use case 2.i "Select a few additional genes". I had 377 preselected genes and wanted to add 100 in addition. The when nicely but when I reload the data and try to plot the masked_dotplot with `sp.pl.masked_dotplot(results.adata, results, ct_key=celltype_key, )`, I get following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[96], line 1
----> 1 sp.pl.masked_dotplot(results.adata, results, ct_key=celltype_key, )

File ~/miniconda3/envs/xenium/lib/python3.9/site-packages/spapros/plotting/plot.py:1596, in masked_dotplot(adata, selector, ct_key, imp_threshold, celltypes, n_genes, comb_markers_only, markers_only, cmap, comb_marker_color, marker_color, non_adata_celltypes_color, save)
   1594 tmp = []
   1595 for markers_celltypes in selector.probeset["celltypes_marker"].str.split(","):
-> 1596     tmp += markers_celltypes
   1597 tmp = np.unique(tmp).tolist()
   1598 if "" in tmp:

TypeError: 'float' object is not iterable
```

The problem seems to be that in the resulting probeset some values in `results.probeset["celltypes_marker"]` are NaN. When I simply remove these values with `results.probeset = results.probeset[results.probeset["celltypes_marker"].notna()]`, I can plot the marked_dotplot. But then of course I lose these selected genes in the later steps.

**Expected behavior**

I expect marked_dotplot to ignore NaNs in the "celltypes_marker" column. Or should genes that are no cell type markers be excluded? I thought these genes would be genes that capture general transcriptomic variation and could also be meaningful. Or am I wrong here?

**System:**

-   OS: SUSE Linux Enterprise Server 15 SP1
-   Language Version: Python 3.9.12
-   Virtual environment: Conda

Thanks a lot in advance for your help!

**Comment by LouisK92** [comment]
Will be solved with commit e3ce3a86ddab7e88ce927dd82ea518ec51f07679. 

- `selector.probeset` is now also loaded when initializing the `selector` from an existing results dir.
- After loading, the NaNs in columns with `dtype == "object"` are converted into empty strings.
