### ISSUE TITLE
Matplotlib compatability

### ISSUE THREAD

**Issue by Laolga** [theislab/spapros#310]
After the initial package installation, the import was not functioning because of matplotlib. As suggested in [previous issues](https://github.com/theislab/spapros/issues/244), I've downgraded to 3.5.3, but now scanpy does not work properly
**To Reproduce**

```
import scanpy as sc
import spapros as sp
adata = sc.datasets.pbmc3k()
adata_tmp = sc.datasets.pbmc3k_processed()

# Get infos from the processed dataset
adata = adata[adata_tmp.obs_names,adata_tmp.var_names]
adata.obs['celltype'] = adata_tmp.obs['louvain']
adata.obsm['X_umap'] = adata_tmp.obsm['X_umap']
del adata_tmp

# Preprocess counts and get highly variable genes
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata,flavor="cell_ranger",n_top_genes=1000)

sc.pl.umap(adata,color="celltype")
```
This code produces:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/olga/anaconda3/envs/spapros2/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py", line 691, in umap
    return embedding(adata, 'umap', **kwargs)
  File "/data/olga/anaconda3/envs/spapros2/lib/python3.9/site-packages/scanpy/plotting/_tools/scatterplots.py", line 165, in embedding
    cmap = copy(colormaps.get_cmap(cmap))
AttributeError: 'ColormapRegistry' object has no attribute 'get_cmap'
```

**System:**

-   OS: CentOS Linux
-   Language Version: Python 3.9
-   Virtual environment:  Conda

**Comment by LouisK92** [comment]
Thanks for reporting!

I could replicate the error. The problem seems to be spapros' depenency constraints on the `upsetplot` package. 

A quick fix would be upgrading that package after installing spapros (and ignoring pip's dependency error):
```
pip install upsetplot --upgrade
```

I'll update the dependency constraints.

**Comment by LouisK92** [comment]
Should be finally solved by updating dependencies with release of 0.1.5
