### ISSUE TITLE
Python version compatibility

### ISSUE THREAD

**Issue by JBreunig** [theislab/spapros#311]
Can you bump the Python compatibility up to more recent version? I'm getting the following error on most workstations (most are using 3.11.5).  Or is there a workaround that I don't know about? Thanks in advance!

> ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.7.1,<3.10; 0.1.1 Requires-Python >=3.7.1,<3.10; 0.1.2 Requires-Python >=3.7.1,<3.10; 0.1.3 Requires-Python >=3.7.1,<3.10; 0.1.4 Requires-Python >=3.7.1,<3.10
> ERROR: Could not find a version that satisfies the requirement spapros (from versions: none)
> ERROR: No matching distribution found for spapros
>

**Comment by LouisK92** [comment]
Thanks for reporting the issue!

Yes, am working on updating tests and setting up CI for python 3.11. Will update in the next 1, 2 weeks. 

Can you use a conda env with python 3.10 instead for now?

**Comment by JBreunig** [comment]
Will do, thanks!
