### ISSUE TITLE
probe set evaluation without sc-RNA-seq reference

### ISSUE THREAD

**Issue by KunHHE** [theislab/spapros#387]
Hi @LouisK92 Very cool to develop this tool for spatial gene detection! Can we perform evaluation directly using Spapros package using a.csv file with, for example,a 300-gene panel list? Without importing a sc-RNA-seq reference. 

Many Thanks!

Kun

**Comment by LouisK92** [comment]
Hi Kun, thanks for reaching out!

We always assume to have an scRNAseq reference on which the evaluations can be run. Our evaluation tools mainly test for cell type classification accuracy, variation recovery, and gene redundancy. Other than that probe design considerations can be assessed without an scRNAseq reference. Technology and species are needed as input for that.  

What would you specifically like to evaluate your gene panel for? If an scRNAseq dataset is needed maybe a public one e.g. from cell x gene could help?

**Comment by KunHHE** [comment]
Hi @LouisK92 Thanks for you quick response. In some of my case, I work for customer-derived project, so in some case the customer can hand me their draft panel list for spatial run, merscope, xenium. So just wander if this package, I can import a gene list and perform some evaluation like you mentioned " cell type classification accuracy, variation recovery, and gene redundancy". 

Best

**Comment by LouisK92** [comment]
We have a few functionalities to evaluate any list of genes (you can simply load the list of genes e.g. with `pd.read_csv("path/to/genes.csv")` and then convert the genes column to a list). However, the evaluation always needs to be done in the context of a scRNAseq reference that is related to the tissue you planned your spatial experiment for. 

In our evaluation tutorials you can find how to run the evaluations: 
https://spapros.readthedocs.io/en/latest/_tutorials/spapros_tutorial_basic_evaluation.html 
https://spapros.readthedocs.io/en/latest/_tutorials/spapros_tutorial_advanced_evaluation.html

**Comment by KunHHE** [comment]
Thank you so much!!! Can I ask 2 more questions:
1. Can I double-check, when using "selector = sp.se.ProbesetSelector(adata, n=140, celltype_key="cell_type", verbosity=1, save_dir=None)", no matter how n=X (140/300 or 500 number of genes), the Note will be the same saying: The following celltypes' test set sizes for forest training are below min_test_n (=20)"? 
2. I finished "selector.select_probeset()" and "selector.probeset", but when tried to run "sp.pl.masked_dotplot(adata, selector)", there's an error showed:
3. 
KeyError                                  Traceback (most recent call last)
File ~\miniconda3\envs\spapro\lib\site-packages\pandas\core\indexes\base.py:3805, in Index.get_loc(self, key)
   3804 try:
-> 3805     return self._engine.get_loc(casted_key)
   3806 except KeyError as err:

File index.pyx:167, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:196, in pandas._libs.index.IndexEngine.get_loc()

File pandas\\_libs\\hashtable_class_helper.pxi:7081, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\\_libs\\hashtable_class_helper.pxi:7089, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'celltype'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[155], line 1
----> 1 sp.pl.masked_dotplot(adata, selector)

File ~\miniconda3\envs\spapro\lib\site-packages\spapros\plotting\plot.py:1578, in masked_dotplot(adata, selector, ct_key, imp_threshold, celltypes, n_genes, comb_markers_only, markers_only, cmap, comb_marker_color, marker_color, non_adata_celltypes_color, use_raw, save)
   1575 from spapros.selection import ProbesetSelector
   1577 if isinstance(selector, str):
-> 1578     selector = ProbesetSelector(adata, ct_key, save_dir=selector)
   1579     # TODO: think the last steps of the ProbesetSelector are still not saved..., needs to be fixed.
   1580 
   1581 # celltypes, possible origins:
   1582 # - adata.obs[ct_key] (could include cts not used for selection)
   1583 # - celltypes for selection (including markers, could include cts which are not in adata.obs[ct_key])
   1584 # --> pool all together... order?
   1586 if celltypes is not None:

File ~\miniconda3\envs\spapro\lib\site-packages\spapros\selection\selection_procedure.py:393, in ProbesetSelector.__init__(self, adata, celltype_key, genes_key, n, preselected_genes, prior_genes, n_pca_genes, min_mean_difference, n_min_markers, celltypes, marker_list, n_list_markers, marker_corr_th, pca_penalties, DE_penalties, m_penalties_adata_celltypes, m_penalties_list_celltypes, pca_selection_hparams, DE_selection_hparams, forest_hparams, forest_DE_baseline_hparams, add_forest_genes_hparams, marker_selection_hparams, verbosity, seed, save_dir, n_jobs)
    391 self.min_mean_difference = min_mean_difference
    392 self.n_min_markers = n_min_markers
--> 393 self.celltypes = self.adata.obs[self.ct_key].unique().tolist() if (celltypes == "all") else celltypes
    394 # All celltypes in adata
    395 self.adata_celltypes = self.adata.obs[self.ct_key].unique().tolist()

File ~\miniconda3\envs\spapro\lib\site-packages\pandas\core\frame.py:4102, in DataFrame.__getitem__(self, key)
   4100 if self.columns.nlevels > 1:
   4101     return self._getitem_multilevel(key)
-> 4102 indexer = self.columns.get_loc(key)
   4103 if is_integer(indexer):
   4104     indexer = [indexer]

File ~\miniconda3\envs\spapro\lib\site-packages\pandas\core\indexes\base.py:3812, in Index.get_loc(self, key)
   3807     if isinstance(casted_key, slice) or (
   3808         isinstance(casted_key, abc.Iterable)
   3809         and any(isinstance(x, slice) for x in casted_key)
   3810     ):
   3811         raise InvalidIndexError(key)
-> 3812     raise KeyError(key) from err
   3813 except TypeError:
   3814     # If we have a listlike key, _check_indexing_error will raise
   3815     #  InvalidIndexError. Otherwise we fall through and re-raise
   3816     #  the TypeError.
   3817     self._check_indexing_error(key)

KeyError: 'celltype'

My reference data frame: AnnData object with n_obs × n_vars = 5218 × 21069
    obs: 'FACS.selection', 'age', 'cell', 'free_annotation', 'method', 'donor_id', 'subtissue', 'n_genes', 'n_counts', 'louvain', 'leiden', 'assay_ontology_term_id', 'disease_ontology_term_id', 'cell_type_ontology_term_id', 'tissue_ontology_term_id', 'development_stage_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'sex_ontology_term_id', 'is_primary_data', 'organism_ontology_term_id', 'suspension_type', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'age_colors', 'citation', 'leiden', 'louvain', 'neighbors', 'pca', 'schema_reference', 'schema_version', 'title', 'log1p', 'hvg', 'cell_type_colors'
    obsm: 'X_pca', 'X_tsne', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

**Comment by KunHHE** [comment]
Thanks so much!
