### ISSUE TITLE
the select_set and dotplot show gene names but not by ensembl_ID

### ISSUE THREAD

**Issue by KunHHE** [theislab/spapros#388]
Hi @LouisK92, Do you know there are any way to show gene names but not by ensembl_ID, in the case of reference like this? Not sure how spapros expects gene names to be passed in the masked_dotplot function. Thanks again!!!

1. selected_set = selector.probeset.index[selector.probeset.selection]
selected_set
Shows: Index(['ENSMUSG00000054641', 'ENSMUSG00000021190', 'ENSMUSG00000024675',
       'ENSMUSG00000030579', 'ENSMUSG00000039405', 'ENSMUSG00000079547',
       'ENSMUSG00000002033', 'ENSMUSG00000002204', 'ENSMUSG00000002985',
       'ENSMUSG00000033022',
       ...
       'ENSMUSG00000022659', 'ENSMUSG00000022564', 'ENSMUSG00000031520',
       'ENSMUSG00000051682', 'ENSMUSG00000007279', 'ENSMUSG00000010358',
       'ENSMUSG00000031838', 'ENSMUSG00000040289', 'ENSMUSG00000033220',
       'ENSMUSG00000033213'],
      dtype='object', length=140)

2. masked_dotplot = sp.pl.masked_dotplot(adata_00, selector)
masked_dotplot.set_size_inches(18.5, 10.5)
masked_dotplot
Shows: ![Image](https://github.com/user-attachments/assets/5f47ef35-33f0-47b4-840b-e33fe807cc53)

**Comment by LouisK92** [comment]
Hey,

to get the plot with gene symbols you need gene symbols in `adata_00.var.index` and in `selector.probeset.index`. I.e. a mapping from ensemble ids to gene symbols is required. 

I showcase this on the following example (in that `adata` we have the gene symbols and ensemble ids in `adata.var`):

```python

# Taking the data example of the tutorials
adata = sc.datasets.pbmc3k()
adata_tmp = sc.datasets.pbmc3k_processed()
adata = adata[adata_tmp.obs_names,adata_tmp.var_names]
adata.obs['celltype'] = adata_tmp.obs['louvain']
adata.obsm['X_umap'] = adata_tmp.obsm['X_umap']
del adata_tmp
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata,flavor="cell_ranger",n_top_genes=1000)


# Set ensemble ids as index to reproduce the issue
adata.var['gene_symbols'] = adata.var_names
adata.var.index = adata.var['gene_ids']

# Gene panel selection
selector = sp.se.ProbesetSelector(adata, n=20, celltype_key="celltype", verbosity=1)
selector.select_probeset()

# Sanity check, the selector.probeset.index contains ensembl ids
selected_set = selector.probeset.index[selector.probeset.selection]
print(selected_set)

# And the masked dotplot shows ensembl ids
sp.pl.masked_dotplot(adata, selector)

# Solution: set the indeces of selector.probeset and adata.var to the gene symbols
selector.probeset.index = adata.var.loc[selector.probeset.index, 'gene_symbols'].values
adata.var.index = adata.var['gene_symbols']

# Now the masked dotplot shows gene symbols
sp.pl.masked_dotplot(adata, selector)
```
